version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms8g -Xmx8g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      esnet:
        ipv4_address: 172.22.0.2
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.2
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms8g -Xmx8g"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      esnet:
        ipv4_address: 172.22.0.3
  btscore:
    build:
      context: .
      args:
        TAG: master
    volumes:
      - ./bts-data:/data_dir
    networks:
      esnet:
        ipv4_address: 172.22.0.4
    command: /app/witness_node --data-dir /data_dir --rpc-endpoint "0.0.0.0:8090" --plugins "elasticsearch market_history grouped_orders" --elasticsearch-node-url "http://172.22.0.2:9200/"
volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  esnet:
    ipam:
      config:
        - subnet: 172.22.0.0/24
          gateway: 172.22.0.1
